services:
  # Backend Service
  - type: web
    name: css-backend
    env: node
    plan: free
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000

  # Frontend Service
  - type: web
    name: css-frontend
    env: static
    plan: free
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
